[runtime]
log_level = "INFO"

[normalize]
workers = 1

[load]
workers = 1
parallelism_strategy = "sequential"

[[sftp_providers.ahl.routes]]
name = "fym_policy"
file_glob = "ahl/inbound/*.csv"
parser = "csv"
table_name = "ahl_fym_policy"
parser_options = { dtype = "string", keep_default_na = false }

[[sftp_providers.manhattan.routes]]
name = "policy"
file_glob = "manhattan/inbound/*.csv"
parser = "csv"
table_name = "manhattan_policy"
parser_options = { dtype = "string", keep_default_na = false }

[[sftp_providers.unl.routes]]
name = "fym_policy"
file_glob = "unl/inbound/UNLFYM_Policy_*.csv"
parser = "csv"
table_name = "unl_fym_policy"
parser_options = { dtype = { zip = "string", issue_date = "string", app_recvd_date = "string", paid_to_date = "string", billing_mode = "string" } }

[[sftp_providers.unl.routes]]
name = "gtl_fym_policy"
file_glob = "unl/inbound/GTLFYM_Policy_*.csv"
parser = "csv"
table_name = "gtl_fym_policy"
parser_options = { dtype = "string", keep_default_na = false }

[[sftp_providers.unl.routes]]
name = "life_professionals_policy"
file_glob = "unl/inbound/LifeProfessionals_Policy_*.csv"
parser = "csv"
table_name = "unl_life_professionals_policy"

[[sftp_providers.unl.routes]]
name = "weekly_commissions"
file_glob = "unl/inbound/CommissionStatements/WC_*.csv"
parser = "csv"
table_name = "unl_weekly_commissions"

[[sftp_providers.unl.routes]]
name = "monthly_commissions"
file_glob = "unl/inbound/CommissionStatements/MC_*.csv"
parser = "csv"
table_name = "unl_monthly_commissions"

[[sftp_providers.unl.routes]]
name = "weekly_advance_statements"
file_glob = "unl/inbound/CommissionStatements/WA_*.csv"
parser = "csv"
table_name = "unl_weekly_advance_statements"

[[sftp_providers.unl.routes]]
name = "monthly_advance_statements"
file_glob = "unl/inbound/CommissionStatements/MA_*.csv"
parser = "csv"
table_name = "unl_monthly_advance_statements"
